
-- CUSTOMER BEHAVIOR SHOPPING ANALYSIS-2

SELECT * FROM customer

-- Business Insights Questions:

-- Q1. Which category generates highest revenue?
SELECT category, ROUND(SUM(purchase_amount::NUMERIC),2) AS highest_revenue 
FROM customer
GROUP BY category
ORDER BY highest_revenue DESC;

-- Q2. Are discounts actually increasing purchase value?
SELECT discount_applied, ROUND(SUM(purchase_amount::NUMERIC),2) AS total_revenue,
ROUND(AVG(purchase_amount::NUMERIC),2) AS avg_revenue
FROM customer
GROUP BY discount_applied

-- Q3. What is the total revenue generated by male and female customer?
SELECT gender, ROUND(SUM(purchase_amount::NUMERIC),2) AS total_revenue
FROM customer
GROUP BY gender

-- Q4. Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, discount_applied, purchase_amount FROM customer 
WHERE discount_applied = 'Yes' AND purchase_amount >(SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC
LIMIT 10;

-- Q5. Which are the top 5 products with the highest average review rating.
SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),1) AS avg_review_rating FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Q6. Which are the bottom 5 products with the highest average review rating.
SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),1) AS avg_review_rating FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating
LIMIT 5;

-- Q7. Average purchase: Standard Vs Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount)) AS avg_purchase
FROM customer
WHERE shipping_type in ('Express','Standard')
GROUP BY shipping_type;

-- Q8. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(DISTINCT customer_id) AS num_of_customer,
ROUND(AVG(purchase_amount)) AS avg_spend,
ROUND(SUM(purchase_amount)) AS total_revenue 
FROM customer
GROUP BY subscription_status;

-- Q9. Top 10 products with highest discount usage.
SELECT item_purchased, COUNT(item_purchased) AS total_num_of_time_item_sold,
COUNT(discount_applied_yes) AS total_num_of_time_sold_when_discount_applied,
COUNT(discount_applied_yes) * 100 / COUNT(*)  AS percent_of_discount_applied
FROM
	(SELECT item_purchased , discount_applied, CASE 
		WHEN discount_applied = 'Yes' THEN 1
		END AS discount_applied_yes
	FROM customer)
GROUP BY item_purchased
ORDER BY percent_of_discount_applied DESC
LIMIT 10;

-- Q10. Segment customer into new, returning and loyal based on their total number of previous purchased,
-- and show the count of each segment.
WITH customer_segments AS (SELECT *,  
	CASE 
		WHEN previous_purchases = 0 THEN 'New'
		WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS segment
FROM customer)
SELECT segment, COUNT(segment) AS customer_segment
FROM customer_segments
GROUP BY segment
ORDER BY customer_segment DESC;

-- Q11. What are the top 3 most purchased products within each category?
WITH top_rank AS(
SELECT category, item_purchased, COUNT(*) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS ranking
FROM customer
GROUP BY category, item_purchased
)
SELECT * FROM top_rank
WHERE ranking <= 3;

-- Q12. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(previous_purchases) AS total_pre_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q13. What is the revenue contribution of each age group?
SELECT age_group, ROUND(SUM(purchase_amount)) AS total_revenue 
FROM (SELECT *,
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN age BETWEEN 26 AND 35 THEN '26-40'
		WHEN age BETWEEN 36 AND 45 THEN '41-60'
		ELSE '60+'
	END AS age_group
FROM customer)
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q14. Most use payment method.
SELECT payment_method, COUNT(*) AS total_num_of_order_placed_by,
ROUND(SUM(purchase_amount)) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY total_num_of_order_placed_by DESC, total_revenue DESC;

-- Q15. Season wise purchases.
SELECT season, COUNT(*) AS total_orders, ROUND(SUM(purchase_amount)) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC, total_orders DESC;

-- Q16. Top 5 Location based on purchase.
SELECT location, COUNT(*) AS total_orders, ROUND(SUM(purchase_amount)) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC, total_orders DESC
LIMIT 5;